import React from 'react'
import './popup.styles.css'

// function deactivatePopup(e) {
//     if (e.target.className.includes('popup-wrapper')) console.log('yep')
// }

function Popup( {active, deactivatePopup} ) {
    return (
        <div className={`popup-wrapper ${active ? 'popup--active' : null}`} onClick={(e) => deactivatePopup(e)}>
            <div className="popup">
                <div className="popup__container">
                    <div className="popup__container__tag">оновлення</div>
                    <div className="popup__container__date">Сьогодні 29.05.2019</div>
                    <div className="popup__container__title">Нові функції моніторингу</div>
                    <div className="popup__container__content">Додайте свою компанію та головних контрагентів до моніторингу та першим дізнавайтесь про істотні зміни офіційних даних.</div>
                    <div className="popup__container__list">
                        <li className="popup__container__list__element">
                            <span>Нові кольори;</span>
                            <img className="popup__container__list__element__img" src="/You-Control/icons/check-mark.svg" alt="" />
                        </li>
                        <li className="popup__container__list__element">
                            <span>Додавайте більше списків.</span>
                            <img className="popup__container__list__element__img" src="/You-Control/icons/check-mark.svg" alt="" />
                        </li>
                    </div>
                    <div className="popup__container__inner-window">
                        <img src="/You-Control/images/suppliers.png" alt="Постачальники" />
                        <img src="/You-Control/images/color-palette.png" alt="Кольори" />

                    </div>
                    <div className="popup__container__whats-new">
                        <div className="popup__container__whats-new__title">Що нового?</div>
                        <div className="popup__container__whats-new__content">Якщо ви поставите в моніторинг власне підприємство, то отримаєте автоматичне сповіщення, якщо його дані в реєстрах змінилися без вашої участі. Зі звіту моніторингу ви можете дізнатися про нього навіть раніше співробітників самого підприємства, адже сповіщення з’явиться того самого дня. За своєю ініціативою контрагент навряд чи повідомить вам цю інформацію, а вона може бути критично важливою для вашої співпраці.</div>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nec ex ut diam commodo sagittis. Nunc rutrum posuere purus at egestas. Sed ac ex sit amet eros semper malesuada at nec orci. Curabitur eget mi sed odio pulvinar tincidunt ac accumsan est. Integer eget urna efficitur, sollicitudin felis id, posuere nisi. Mauris sed turpis lacus. In at urna ipsum. Aliquam libero mauris, fringilla vel leo a, hendrerit varius est. In hac habitasse platea dictumst. Vivamus placerat urna id enim sollicitudin, ac consectetur justo luctus. Maecenas tempus erat eu tellus accumsan aliquet. Integer dapibus dictum tempor. Quisque hendrerit et orci vitae dictum.Nullam a vehicula mauris, vel dignissim massa. Curabitur nec enim varius, iaculis augue vel, sollicitudin lectus. Nam eleifend lorem quis accumsan lacinia. Vivamus et quam nulla. Nulla rutrum augue et purus malesuada, auctor consequat neque venenatis. Phasellus auctor eget libero at aliquet. Duis sed justo vel risus condimentum tempus non sed metus. Morbi vitae faucibus massa, ac rutrum risus. Phasellus aliquet pulvinar ullamcorper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras ut tempus leo. Suspendisse potenti. Quisque consequat metus nec erat gravida commodo. Pellentesque ut dolor at purus consectetur gravida. Aenean malesuada sapien ac nisi consectetur eleifend. Cras fringilla blandit lorem eget sollicitudin. Proin ac nisl ut enim sagittis lacinia. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque tempor malesuada ante vel rhoncus. Mauris finibus vehicula justo, eu luctus massa. Donec vestibulum diam vitae commodo sodales. Vestibulum rhoncus dolor eget porttitor accumsan. Etiam vitae feugiat magna, id porta mauris. Nullam imperdiet odio a sapien aliquam, pharetra vestibulum nibh pharetra. Proin convallis ante nisi, et congue ipsum gravida id. Curabitur tempor tempor nisi, at auctor diam elementum vitae. Duis interdum vitae nulla id ullamcorper. Phasellus ante ante, ultricies non faucibus ac, tristique vitae ex. Etiam in faucibus dolor. Pellentesque eu urna sed ex molestie suscipit quis sit amet neque. Ut commodo pharetra lacus, ac dignissim metus aliquam quis. Praesent eget mi ultricies, mattis nunc non, commodo mauris. Donec sagittis ligula id aliquam convallis. Quisque mattis quis mauris in posuere. Phasellus eu ex eu risus sollicitudin aliquet ut at massa. Cras sollicitudin sollicitudin sagittis. Mauris eu sodales eros, nec ullamcorper orci. Duis at mauris quis justo pulvinar eleifend eget eu eros. Curabitur ut mi ac ex blandit tincidunt. Pellentesque at sapien non dolor molestie pulvinar non nec quam. Suspendisse auctor diam purus, at pretium quam pellentesque auctor. Donec tristique pulvinar ante sed vehicula.
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nec ex ut diam commodo sagittis. Nunc rutrum posuere purus at egestas. Sed ac ex sit amet eros semper malesuada at nec orci. Curabitur eget mi sed odio pulvinar tincidunt ac accumsan est. Integer eget urna efficitur, sollicitudin felis id, posuere nisi. Mauris sed turpis lacus. In at urna ipsum. Aliquam libero mauris, fringilla vel leo a, hendrerit varius est. In hac habitasse platea dictumst. Vivamus placerat urna id enim sollicitudin, ac consectetur justo luctus. Maecenas tempus erat eu tellus accumsan aliquet. Integer dapibus dictum tempor. Quisque hendrerit et orci vitae dictum.Nullam a vehicula mauris, vel dignissim massa. Curabitur nec enim varius, iaculis augue vel, sollicitudin lectus. Nam eleifend lorem quis accumsan lacinia. Vivamus et quam nulla. Nulla rutrum augue et purus malesuada, auctor consequat neque venenatis. Phasellus auctor eget libero at aliquet. Duis sed justo vel risus condimentum tempus non sed metus. Morbi vitae faucibus massa, ac rutrum risus. Phasellus aliquet pulvinar ullamcorper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras ut tempus leo. Suspendisse potenti. Quisque consequat metus nec erat gravida commodo. Pellentesque ut dolor at purus consectetur gravida. Aenean malesuada sapien ac nisi consectetur eleifend. Cras fringilla blandit lorem eget sollicitudin. Proin ac nisl ut enim sagittis lacinia. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque tempor malesuada ante vel rhoncus. Mauris finibus vehicula justo, eu luctus massa. Donec vestibulum diam vitae commodo sodales. Vestibulum rhoncus dolor eget porttitor accumsan. Etiam vitae feugiat magna, id porta mauris. Nullam imperdiet odio a sapien aliquam, pharetra vestibulum nibh pharetra. Proin convallis ante nisi, et congue ipsum gravida id. Curabitur tempor tempor nisi, at auctor diam elementum vitae. Duis interdum vitae nulla id ullamcorper. Phasellus ante ante, ultricies non faucibus ac, tristique vitae ex. Etiam in faucibus dolor. Pellentesque eu urna sed ex molestie suscipit quis sit amet neque. Ut commodo pharetra lacus, ac dignissim metus aliquam quis. Praesent eget mi ultricies, mattis nunc non, commodo mauris. Donec sagittis ligula id aliquam convallis. Quisque mattis quis mauris in posuere. Phasellus eu ex eu risus sollicitudin aliquet ut at massa. Cras sollicitudin sollicitudin sagittis. Mauris eu sodales eros, nec ullamcorper orci. Duis at mauris quis justo pulvinar eleifend eget eu eros. Curabitur ut mi ac ex blandit tincidunt. Pellentesque at sapien non dolor molestie pulvinar non nec quam. Suspendisse auctor diam purus, at pretium quam pellentesque auctor. Donec tristique pulvinar ante sed vehicula.
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nec ex ut diam commodo sagittis. Nunc rutrum posuere purus at egestas. Sed ac ex sit amet eros semper malesuada at nec orci. Curabitur eget mi sed odio pulvinar tincidunt ac accumsan est. Integer eget urna efficitur, sollicitudin felis id, posuere nisi. Mauris sed turpis lacus. In at urna ipsum. Aliquam libero mauris, fringilla vel leo a, hendrerit varius est. In hac habitasse platea dictumst. Vivamus placerat urna id enim sollicitudin, ac consectetur justo luctus. Maecenas tempus erat eu tellus accumsan aliquet. Integer dapibus dictum tempor. Quisque hendrerit et orci vitae dictum.Nullam a vehicula mauris, vel dignissim massa. Curabitur nec enim varius, iaculis augue vel, sollicitudin lectus. Nam eleifend lorem quis accumsan lacinia. Vivamus et quam nulla. Nulla rutrum augue et purus malesuada, auctor consequat neque venenatis. Phasellus auctor eget libero at aliquet. Duis sed justo vel risus condimentum tempus non sed metus. Morbi vitae faucibus massa, ac rutrum risus. Phasellus aliquet pulvinar ullamcorper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras ut tempus leo. Suspendisse potenti. Quisque consequat metus nec erat gravida commodo. Pellentesque ut dolor at purus consectetur gravida. Aenean malesuada sapien ac nisi consectetur eleifend. Cras fringilla blandit lorem eget sollicitudin. Proin ac nisl ut enim sagittis lacinia. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque tempor malesuada ante vel rhoncus. Mauris finibus vehicula justo, eu luctus massa. Donec vestibulum diam vitae commodo sodales. Vestibulum rhoncus dolor eget porttitor accumsan. Etiam vitae feugiat magna, id porta mauris. Nullam imperdiet odio a sapien aliquam, pharetra vestibulum nibh pharetra. Proin convallis ante nisi, et congue ipsum gravida id. Curabitur tempor tempor nisi, at auctor diam elementum vitae. Duis interdum vitae nulla id ullamcorper. Phasellus ante ante, ultricies non faucibus ac, tristique vitae ex. Etiam in faucibus dolor. Pellentesque eu urna sed ex molestie suscipit quis sit amet neque. Ut commodo pharetra lacus, ac dignissim metus aliquam quis. Praesent eget mi ultricies, mattis nunc non, commodo mauris. Donec sagittis ligula id aliquam convallis. Quisque mattis quis mauris in posuere. Phasellus eu ex eu risus sollicitudin aliquet ut at massa. Cras sollicitudin sollicitudin sagittis. Mauris eu sodales eros, nec ullamcorper orci. Duis at mauris quis justo pulvinar eleifend eget eu eros. Curabitur ut mi ac ex blandit tincidunt. Pellentesque at sapien non dolor molestie pulvinar non nec quam. Suspendisse auctor diam purus, at pretium quam pellentesque auctor. Donec tristique pulvinar ante sed vehicula.
                        </p>
                    </div>
                </div>

                <div className="popup__container__btn-container">
                    <button>Назад</button>
                    <button>Наступне сповіщення</button>
                </div>

            </div>

        </div>
    )
}

export default Popup
